name: EnderChestSee
version: '1.0'
main: net.gura.enderChestSee.EnderChestSee
api-version: '1.21'
load: STARTUP
authors: [ Gura ]
description: Minecraft Plugin that allows you to see enderchests of other players
